#!/bin/sh
set -eu

REPL_USER="${MARIADB_REPL_USER:-repl}"
REPL_PASSWORD="${MARIADB_REPL_PASSWORD:-repl_change_me}"

mariadb -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${REPL_USER}'@'%' IDENTIFIED BY '${REPL_PASSWORD}';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${REPL_USER}'@'%';
FLUSH PRIVILEGES;
SQL
